### PR TITLE
Add support for vim-endwise

### PR DESCRIPTION
**Pull request by thetic**
Derived from (seemingly dead) PR: https://github.com/tpope/vim-endwise/pull/97

### CODE REVIEW

**Comment by pboettch** [comment]
Does this make that the `end`-part of a control-statement is automatically when typed?

**Comment by thetic** [comment]
Yes; if the vim-endwise plugin is installed.

**Comment by pboettch** [comment]
Wouldn't it be more logic than to put this in the vim-endwise-plugin?

**Comment by thetic** [comment]
Maybe. I don't think it would be inappropriate to add it here, though. Other syntax plugins do the same.

**Comment by pboettch** [comment]
OK, you're right, why not.

Do you think we could automate a non-regression test for this feature?

**Pull request closed without merging**
