### PR TITLE
Add Doxygen definitions 

### PR DESCRIPTION
**Pull request by MindTooth**
Based on this https://cmake.org/cmake/help/latest/module/FindDoxygen.html.

Tried running the tests, but all failed.  Even on `master`.

Seems okay?

_(I'll be squashing before merging.)_

### CODE REVIEW

**Comment by pboettch** [comment]
I took your PR and added the Doxygen-module to the extractor-script (which is used to generate the syntax-file).

It found many more keywords. Could you verify whether this is OK for you? 

https://github.com/pboettch/vim-cmake-syntax/tree/MindTooth-add_doxygen

**Comment by MindTooth** [comment]
The thing is, that most of the keywords is not CMake per se.  They are in fact Doxygen keywords, and they need to be set as `DOXYGEN_{{KEYWORD}}` before calling `doxygen_add_docs()`.  Meaning just a plain `ABBREVIATE_BRIEF` would not do anything, but `DOXYGEN_BBREVIATE_BRIEF` would.

I do see now that I did manually add some of the config [flags](http://www.doxygen.nl/manual/config.html) that is generated as `DOXYGEN_{{KEYWORD}}`.

What the module in itself exposes is just a tiny fraction of what it accepts, as [show](https://cmake.org/cmake/help/latest/module/FindDoxygen.html).  Did not notice this before now..

How to deal with this, I'm not sure.  But it's not as easy as just extracting without doing some extra tweaking.

**Comment by pboettch** [comment]
I see. Hmm, automatic extraction is indeed limited. The way cmake parses its files is done in a way that finding keywords is hard. The assumption is actually that keyword are mentioned in all upper-case in any of the help-pages for functions.

It's even worse with this Doxygen-module. Well, I think, it has to be done manually. I will put in a thing for people contributing descriptions which will then be integrated when generating the .vim-file.

**Comment by MindTooth** [comment]
Cool.  I’ll follow your work and resubmitting when you’ve implemented it.

**Pull request closed without merging**
